### ISSUE TITLE
修改文章时，再点左侧的编辑文章，页面不刷新不跳转

### ISSUE THREAD

**Issue by lanxkk** [sailengsi/sls-admin#12]
1、修改文章时，比如网址是：https://vue2.slsadmin.sailengsi.com/#/demo/article/edit?id=281

2、点击左侧的“编辑文章”，网址变成：https://vue2.slsadmin.sailengsi.com/#/demo/article/edit

3、这个时候没有任何提示、网页也不刷新不跳转，表单内还是原来修改文章的内容。

4、怎么修改可以正常跳转或刷新页面呢？

**Comment by sailengsi** [comment]
@lanxkk 
对于3和4，麻烦你再描述一下，你的建议和你想要的具体效果？

**Comment by lanxkk** [comment]
建议：正在修改文章时，如果点击左边的”编辑文章“，弹出提示”是否要放弃当前的编辑内容？“。如果选择”是“，则跳转，”否“则不改变。

**Comment by sailengsi** [comment]
@lanxkk 谢谢。
