### ISSUE TITLE
项目build后，无法登陆

### ISSUE THREAD

**Issue by xxyjskx1987** [sailengsi/sls-admin#13]
项目build后，无法登陆

**Comment by sailengsi** [comment]
@xxyjskx1987 dev模式，接口代理用的webpack；build之后，代理就无效了，如果是Apache或者Nginx，可以在配置文件做代理。

**Comment by xxyjskx1987** [comment]
谢谢回复@sailengsi 有没有变量的方式来修改域名，没有找到地方

**Comment by sailengsi** [comment]
@xxyjskx1987 没太懂你的意思，什么是变量的方式修改域名？域名怎么修改？

**Comment by xxyjskx1987** [comment]
@sailengsi 在vue代码里，修改代理

**Comment by sailengsi** [comment]
@xxyjskx1987 webpack代理只在dev模式有效，build之后，代理走的是服务器的上的配置。
不过，如果你线上的host和接口是一个域名的话，你可以动态更改接口的host。

**Comment by lin0123** [comment]
请问下现在是不是无法登陆了???

**Comment by sailengsi** [comment]
@lin0123 可以登录啊。
