### ISSUE TITLE
webpack打包太大，另外有几个疑问

### ISSUE THREAD

**Issue by lilien1010** [sailengsi/sls-admin#15]
有几个疑问想问一下
1：如果后台很多功能的话子页面的话，岂不是webpack打包之后的js文件很大？
2：能不能实现多tap标签，类似这样。
![image](https://cloud.githubusercontent.com/assets/3814966/24543578/b6e3b704-1632-11e7-80fc-60a1d52822e8.png)

**Comment by sailengsi** [comment]
@lilien1010 打包体积大，可以用webpack2的tree shaking功能，我这个系统目前用的webpack1，需要自己构建项目。
tab功能其实也能实现，不过需要考虑下，是怎样的形式？比如什么时候初始化tab？什么时候添加tab？是否需要持久化tab?等一系列需求。
