### ISSUE TITLE
关于封装自定义表格的问题

### ISSUE THREAD

**Issue by liliang1993** [sailengsi/sls-admin#20]
首先对您的该开源项目表示感谢,目前我正在您封装的表格组件基础上做自定义表格的封装,发现没有什么好的思路,希望您有时间封装一个自定义的表格组件即表格各单元项可为可编辑的表单形式.供学习,不好意思,做了伸手党

**Comment by sailengsi** [comment]
@liliang1993 没关系，能用到就好，关于功能上的需求，后面有空的话会慢慢拓展。
