### ISSUE TITLE
关于API get 带 query参数

### ISSUE THREAD

**Issue by Bangood** [sailengsi/sls-admin#28]
请问下，你现在所有的只要有参数请求的api都是使用的post，如果要通过get 带query参数，应该怎么弄啊

**Comment by sailengsi** [comment]
@Bangood 没有啊，也有get啊。比如获取内容列表，增加搜索参数，都是get啊。

**Comment by Bangood** [comment]
@sailengsi 我说的是类似 get   /api/user/:id这样的路由

**Comment by sailengsi** [comment]
@Bangood 哦哦，前两天我朋友也提出了这个问题，有空我加上支持这种模式。
