### ISSUE TITLE
表格中的数据获取方式

### ISSUE THREAD

**Issue by AJinglalala** [sailengsi/sls-admin#29]
您好，我正在使用您的框架搭建一个管理系统，遇到几个问题想请教您
1. 如果想通过一个url获取api数据添加到表格中要如何设置呢
2. 之后的跨域问题要怎么解决呢？
3. url中的数据是实时更新的，是否可以通过添加定时器或使用signalR的方式让列表中的数据也实时更新呢？

**Comment by sailengsi** [comment]
1，获取表格中的某行数据，可以直接通过事件拿到。
2，关于跨域问题，可以参考代理，在文档中  如何使用   章节有说明。
3，URL中的数据实时更新是什么意思？如果要实时更新页面的数据，可以采用第三方推送库，定时器定时查询也可以。

**Comment by AJinglalala** [comment]
好的  谢谢您    我去试一试
