### ISSUE TITLE
左侧菜单的缩回按钮建议放在顶部，而非底部。

### ISSUE THREAD

**Issue by rts-gordon** [sailengsi/sls-admin#4]
左侧菜单的缩回按钮建议放在顶部，用户一般习惯着眼顶部操作按钮，而是底部。

**Comment by sailengsi** [comment]
这个效果我是模仿的gitlab，你说的也有道理。
我做成可配置的吧，让你们自己选择位置。

**Comment by dodio** [comment]
我觉得不必要，我觉得作者已经做了一个脚手架的很大部分的工作了。 这种UI位置级别的，也不宜做成通用的

**Comment by socall92** [comment]
关于左侧菜单，有个建议。
现在没有滚动条，如果菜单列表超出了页面范围，不能下拉。
这个功能能否增加一下。
