### ISSUE TITLE
Dist目录是最终编译混淆的代码，不必做为代码配置项提交到github。

### ISSUE THREAD

**Issue by rts-gordon** [sailengsi/sls-admin#6]
Dist目录是最终编译混淆的代码，不必做为代码配置项提交到github。

**Comment by sailengsi** [comment]
@CHCP  因为服务器上需要访问dist目录，所以我一并提交了。并且我自己的git和GitHub上这个，用的是一个仓库，如果这里不提交dist的话，我需要管理多个仓库，会比较麻烦，这个其实可以忽略。

**Comment by rts-gordon** [comment]
在.gitignore文件中增加dist目录，可以在提交代码时忽略这个目录。
