### ISSUE TITLE
建议把/src/config/request.js中的函数ajax单独成文件

### ISSUE THREAD

**Issue by rts-gordon** [sailengsi/sls-admin#7]
建议把/src/config/request.js中的函数ajax单独成文件，这样再有其他接口需要实现时可以直接调用该函数，而不是一直往request.js中增加函数定义，形成模块化处理。

**Comment by sailengsi** [comment]
@CHCP 不错，好建议，回头一块修改。

**Comment by sailengsi** [comment]
@CHCP 已分离。
